import { BrowserEngine } from '../browser/engine';
import { WindowsControl, getWindowsControl } from '../desktop/windowsControl';
import { ScreenCapture, getScreenCapture } from '../desktop/screenCapture';
import { VSCodeController, getVSCodeController } from '../desktop/vscodeController';

// Computer Use Task Types
export interface ComputerUseTask {
  id: string;
  description: string;
  type:
    | 'web_navigation'
    | 'desktop_operation'
    | 'coding_task'
    | 'research'
    | 'monitoring'
    | 'complex_workflow'
    | 'build_app'
    | 'test_app'
    | 'self_improve';
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  priority: 'low' | 'medium' | 'high' | 'critical';
  timeout?: number;
  context?: ComputerContext;
  subtasks?: ComputerUseTask[];
  dependencies?: string[];
  startedAt?: Date;
  completedAt?: Date;
  result?: any;
  error?: string;
  metadata?: Record<string, any>;
}

export interface ComputerContext {
  activeWindow?: string;
  openApplications?: string[];
  currentUrl?: string;
  screenState?: ScreenState;
  clipboard?: string;
  timestamp: Date;
}

export interface ScreenState {
  screenshot?: Buffer;
  activeElement?: UIElement;
  mousePosition?: { x: number; y: number };
  changedRegions?: Array<{ x: number; y: number; width: number; height: number }>;
}

export interface UIElement {
  name: string;
  controlType: string;
  boundingRectangle: { x: number; y: number; width: number; height: number };
  isEnabled: boolean;
  isOffscreen: boolean;
  children?: UIElement[];
  automationId?: string;
}

// Computer Use Tools
export interface ComputerTool {
  name: string;
  description: string;
  capabilities: string[];
  execute: (params: any, context?: ComputerContext) => Promise<any>;
}

// Computer Use Result
export interface ComputerUseResult {
  success: boolean;
  data?: any;
  error?: string;
  context: ComputerContext;
  executionTime: number;
  toolUsed: string;
  screenshot?: Buffer;
  logs?: ExecutionLogEntry[];
}

// High-level Computer Operations
export interface ComputerOperation {
  type:
    | 'open_application'
    | 'close_application'
    | 'navigate_web'
    | 'take_screenshot'
    | 'type_text'
    | 'click_element'
    | 'edit_file'
    | 'run_command'
    | 'monitor_screen'
    | 'build_project'
    | 'run_server'
    | 'test_application'
    | 'deploy_application'
    | 'extract_page_content'
    | 'terminal_run'
    | 'browser_screenshot'
    | 'browser_type'
    | 'browser_click'
    | 'vscode_edit'
    | 'vscode_write'
    | 'browser_get_elements'
    | 'browser_get_accessibility_tree'
    | 'desktop_get_windows'
    | 'desktop_launch_app'
    | 'npm_install';
  target?: string;
  parameters?: Record<string, any>;
  description?: string;
}

// Autonomous Digital Operator Configuration
export interface DigitalOperatorConfig {
  name: string;
  role: string;
  capabilities: string[];
  llmModel: string;
  visionEnabled: boolean;
  maxConcurrentTasks: number;
  securityLevel: 'low' | 'medium' | 'high' | 'maximum';
  workspace: string;
  tools: {
    browser: boolean;
    desktop: boolean;
    vscode: boolean;
    screen: boolean;
    filesystem: boolean;
  };
}

// ============================================================================
// AUTONOMOUS AGENT TYPES (KiloCode 2.0 Integration)
// ============================================================================

/**
 * Execution plan generated by TaskPlanner for complex autonomous tasks
 */
export interface ExecutionPlan {
  id: string;
  goal: string;
  steps: ExecutionStep[];
  estimatedDuration: number;
  requiredCapabilities: string[];
  status: 'draft' | 'approved' | 'executing' | 'completed' | 'failed';
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Individual step in an execution plan
 */
export interface ExecutionStep {
  id: string;
  planId: string;
  order: number;
  type: 'research' | 'code' | 'test' | 'deploy' | 'browser' | 'monitor' | 'notify' | 'self_improve';
  description: string;
  tool: string;
  params: Record<string, any>;
  status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'skipped';
  result?: any;
  error?: string;
  retryCount: number;
  maxRetries: number;
  startedAt?: Date;
  completedAt?: Date;
}

/**
 * Comprehensive execution log entry
 */
export interface ExecutionLogEntry {
  id: string;
  timestamp: Date;
  level: 'debug' | 'info' | 'warn' | 'error' | 'critical';
  category:
    | 'planning'
    | 'research'
    | 'coding'
    | 'testing'
    | 'browser'
    | 'deployment'
    | 'self_improvement'
    | 'notification';
  message: string;
  data?: Record<string, any>;
  taskId?: string;
  stepId?: string;
  planId?: string;
}

/**
 * Self-improvement capability definition
 */
export interface Capability {
  id: string;
  name: string;
  description: string;
  category: 'browser' | 'code' | 'api' | 'integration' | 'analysis';
  code: string; // Implementation code or MCP server config
  source: 'built_in' | 'user_created' | 'auto_generated';
  version: string;
  isActive: boolean;
  dependencies: string[];
  createdAt: Date;
  lastUsedAt?: Date;
}

/**
 * Goal notification payload
 */
export interface GoalNotification {
  goalId: string;
  goalDescription: string;
  status: 'completed' | 'failed' | 'needs_review';
  summary: string;
  details: {
    tasksCompleted: number;
    tasksFailed: number;
    duration: number;
    logs: ExecutionLogEntry[];
    artifacts: Artifact[];
  };
  timestamp: Date;
  userNotified: boolean;
}

/**
 * Artifact produced during execution (files, apps, reports)
 */
export interface Artifact {
  id: string;
  type: 'file' | 'application' | 'report' | 'screenshot' | 'log';
  name: string;
  path: string;
  metadata: Record<string, any>;
  createdAt: Date;
}

/**
 * Autonomous agent configuration
 */
export interface AutonomousAgentConfig {
  name: string;
  workspace: string;
  llmModel: string;
  visionModel?: string;
  maxConcurrentTasks: number;
  maxRetries: number;
  timeout: number;
  autoNotify: boolean;
  notificationChannels: ('websocket' | 'email' | 'slack')[];
  selfImprovementEnabled: boolean;
  browserConfig: {
    headless: boolean;
    defaultTimeout: number;
    screenshotOnFailure: boolean;
  };
}

/**
 * Agent state for persistence
 */
export interface AgentState {
  id: string;
  config: AutonomousAgentConfig;
  activePlanId?: string;
  capabilities: Capability[];
  stats: {
    tasksCompleted: number;
    tasksFailed: number;
    improvementsApplied: number;
    uptime: number;
    startedAt: Date;
  };
}

/**
 * Universal IDE Interface
 */
export interface IDEController {
  initialize(): Promise<void>;
  open(options?: any): Promise<void>;
  openFile(filePath: string, line?: number): Promise<void>;
  readFile(filePath: string): Promise<string>;
  writeFile(filePath: string, content: string): Promise<void>;
  editFile(edit: any): Promise<void>;
  executeCommand(command: string): Promise<void>;
  runTerminalCommand(command: string): Promise<void>;
}

